name: andeslink-churn-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - pip:
      - mlflow
      - dvc
      - joblib
      - pytest
      - fastapi
      - "uvicorn[standard]"
      - pydantic
      - streamlit
      - requests
      - httpx
